### ISSUE TITLE
PT-BR Language

### ISSUE THREAD

**Issue by DeskTecc** [SphinxHD/Districts#1]
English:
I decided on my own to contribute by helping to translate the plugin into my language, I hope this helps other people too :)
Português:
Eu decidi por conta própria contribuir ajudando a traduzir o plugin na minha linguagem, espero que isso ajude outras pessoas também :)
archive: [locale_pt-BR.zip](https://github.com/SphinxHD/Districts/files/7918954/locale_pt-BR.zip)

**Comment by SphinxHD** [comment]
Hello,
Thank you for the Translation. I will add it in the next few Days.
